title: Ryan Bushe
description: Ryan Bushe

url: http://bushe.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: bushe
   twitter: RyanBushe
   email: Ryan@Bushe.com

google_analytics: ""
